import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarComponent from "./components/NavbarComponent";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pasta Connection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="relative overflow-hidden rounded-lg bg-cover bg-no-repeat"
        style={{
          backgroundImage:
            "linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(/main_page_image2.jpg)",
          height: "100vh",
        }}
      >
        <NavbarComponent />
        {children}
      </body>
    </html>
  );
}
